<?php

namespace App\Modules\Academy\Services;

use App\Modules\Squad\Configs\TeamRegionalOrigins;
use App\Modules\Squad\DTOs\GeneratedPlayerData;
use App\Models\AcademyPlayer;
use App\Models\Game;
use App\Models\GamePlayer;
use App\Modules\Player\PlayerAge;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;
use App\Modules\Player\Services\PlayerDevelopmentService;
use App\Modules\Player\Services\PlayerValuationService;
use App\Modules\Squad\Services\PlayerAttributeSampler;
use App\Modules\Squad\Services\PlayerGeneratorService;
use App\Modules\Squad\Services\SquadNumberService;
use Illuminate\Support\Facades\DB;

class YouthAcademyService
{
    /**
     * Tier configuration: [min_arrivals, max_arrivals]
     */
    private const TIER_CONFIG = [
        0 => [1, 1],
        1 => [2, 3],
        2 => [3, 5],
        3 => [4, 6],
        4 => [4, 6],
    ];

    /**
     * Base average ability for prospects generated by each academy tier.
     * Higher tiers produce better players on average.
     */
    private const ACADEMY_BASE_QUALITY = [
        0 => 38,   // Minimum: raw, unpolished prospect
        1 => 45,   // Basic: developing players
        2 => 52,   // Good: slightly above developing
        3 => 66,   // Elite: average-to-good
        4 => 74,   // World-Class: good, ready to contribute
    ];

    /**
     * Small adjustment to the ability mean based on first team's median tier.
     * Keeps academy output contextually anchored to club strength.
     */
    private const TEAM_CONTEXT_BONUS = [
        1 => -3,
        2 => -1,
        3 => 0,
        4 => 2,
        5 => 4,
    ];

    /**
     * Standard deviation for the ability normal distribution.
     * Uniform across all tiers — only the mean differentiates them.
     */
    private const ABILITY_STD_DEV = 6;

    private const ESTIMATED_MATCHDAYS = 38;

    /**
     * Season growth rates for development.
     * Controls what fraction of (potential - current) is gained per season.
     */
    private const GROWTH_RATE_ACADEMY = 0.25;
    private const GROWTH_RATE_LOAN = 0.35;

    /**
     * Position groups with weights for random selection.
     * First a group is chosen by weight, then a specific position within it.
     */
    private const POSITION_GROUPS = [
        ['weight' => 9,  'positions' => ['Goalkeeper']],
        ['weight' => 33, 'positions' => ['Centre-Back', 'Left-Back', 'Right-Back']],
        ['weight' => 29, 'positions' => ['Defensive Midfield', 'Central Midfield', 'Attacking Midfield']],
        ['weight' => 29, 'positions' => ['Left Winger', 'Right Winger', 'Centre-Forward']],
    ];

    public function __construct(
        private readonly PlayerGeneratorService $playerGenerator,
        private readonly SquadNumberService $squadNumberService,
        private readonly PlayerAttributeSampler $sampler,
        private readonly PlayerDevelopmentService $developmentService,
        private readonly PlayerValuationService $valuationService,
    ) {}

    /**
     * Per-season chance (%) that the academy produces a "jewel" — a
     * standout 16-year-old with elite potential. Higher tiers find them
     * more often; even a bare-bones academy can get lucky.
     */
    private const JEWEL_CHANCE_PER_TIER = [
        0 => 10,
        1 => 20,
        2 => 35,
        3 => 50,
        4 => 65,
    ];

    /**
     * Jewel trait bands. The game engine only models ability as a single
     * overall score (no granular technical/physical/mental stats), so the
     * "position-based attributes" live in the position-specific overall
     * sampling and the position-aware market valuation below.
     */
    private const JEWEL_AGE = 16;
    private const JEWEL_OVERALL_MEAN = 65;
    private const JEWEL_OVERALL_MIN = 58;
    private const JEWEL_OVERALL_MAX = 74;
    private const JEWEL_POTENTIAL_MIN = 78;
    private const JEWEL_POTENTIAL_MAX = 92;

    /**
     * Generate a batch of new academy prospects at season start.
     *
     * For filial games (clubs with a reserve team), prospects are created as
     * full GamePlayers on the reserve squad — no AcademyPlayer rows. For
     * non-filial games, prospects land in the AcademyPlayer pool as before.
     *
     * Each season there is also a periodic chance (see JEWEL_CHANCE_PER_TIER)
     * of the academy producing a "jewel": a 16-year-old standout with elite
     * potential. Pass $forceJewel to guarantee one (used by tests / QA).
     *
     * @return Collection<int, AcademyPlayer|GamePlayer>
     */
    public function generateSeasonBatch(Game $game, bool $forceJewel = false): Collection
    {
        $tier = $game->currentInvestment->youth_academy_tier ?? 0;

        $config = self::TIER_CONFIG[$tier] ?? self::TIER_CONFIG[0];
        [$minArrivals, $maxArrivals] = $config;

        $count = rand($minArrivals, $maxArrivals);
        $teamMedianTier = $this->getTeamMedianTier($game);
        $excludedNames = $this->getExistingPlayerNames($game);

        $prospects = collect();
        $isFilial = $game->reserve_team_id !== null;

        for ($i = 0; $i < $count; $i++) {
            $traits = $this->rollProspectTraits($game, $tier, $teamMedianTier, $excludedNames);

            $prospect = $isFilial
                ? $this->persistAsReservePlayer($game, $traits)
                : $this->persistAsAcademyPlayer($game, $traits);

            $excludedNames[] = $traits['name'];
            $prospects->push($prospect);
        }

        // Periodic jewel: non-filial games keep jewels in the academy pool so
        // the user can spot them (badge) and promote them when ready.
        if (! $isFilial && ($forceJewel || rand(1, 100) <= self::getJewelChance($tier))) {
            $jewel = $this->generateJewel($game, $excludedNames);
            $prospects->push($jewel);
        }

        return $prospects;
    }

    /**
     * Generate one "jewel of the academy": a 16-year-old with standout
     * overall for her age and elite potential, persisted as an AcademyPlayer
     * flagged with is_jewel so the UI can badge her.
     *
     * @param  array<int, string>  $excludedNames
     */
    public function generateJewel(Game $game, array $excludedNames = []): AcademyPlayer
    {
        $position = $this->selectPosition();

        $overallScore = $this->sampler->sampleAbility(
            self::JEWEL_OVERALL_MEAN,
            self::ABILITY_STD_DEV,
            self::JEWEL_OVERALL_MIN,
            self::JEWEL_OVERALL_MAX,
        );

        $potential = rand(self::JEWEL_POTENTIAL_MIN, self::JEWEL_POTENTIAL_MAX);
        $potentialLow = max(60, $potential - rand(2, 5));
        $potentialHigh = min(99, $potential + rand(2, 6));

        $dateOfBirth = $game->current_date->copy()->subYears(self::JEWEL_AGE)->subDays(rand(0, 364));

        $teamName = $game->team->name;
        $nationalityFilter = self::CANTERA_TEAMS[$teamName] ?? null;
        $teamCountry = $nationalityFilter ? null : $game->team->country;
        $region = TeamRegionalOrigins::regionFor($teamName);
        $identity = $this->playerGenerator->pickRandomIdentity(
            $nationalityFilter,
            $teamCountry,
            $excludedNames,
            $region,
        );

        $jewel = $this->persistAsAcademyPlayer($game, [
            'position' => $position,
            'age' => self::JEWEL_AGE,
            'dateOfBirth' => $dateOfBirth,
            'overallScore' => $overallScore,
            'potential' => $potential,
            'potentialLow' => $potentialLow,
            'potentialHigh' => $potentialHigh,
            'name' => $identity['name'],
            'nationality' => $identity['nationality'],
        ]);

        $jewel->update(['is_jewel' => true]);

        return $jewel->fresh();
    }

    /**
     * Per-season jewel chance (%) for an academy tier.
     */
    public static function getJewelChance(int $tier): int
    {
        return self::JEWEL_CHANCE_PER_TIER[$tier] ?? self::JEWEL_CHANCE_PER_TIER[0];
    }

    /**
     * Develop all academy players' abilities for one matchday.
     * Growth is applied each matchday as a small increment toward potential.
     * Only non-loaned players develop (loaned develop at season end).
     */
    public function developPlayers(Game $game): void
    {
        $players = AcademyPlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->where('is_on_loan', false)
            ->get();

        if ($players->isEmpty()) {
            return;
        }

        // Compute growth in memory, batch persist changed players in a single query
        $updates = []; // [id => ['overall_score' => int, 'growth_progress' => float]]
        foreach ($players as $player) {
            $computed = $this->computeGrowth($player, self::GROWTH_RATE_ACADEMY);
            if ($computed !== null) {
                $updates[$player->id] = $computed;
            }
        }

        if (! empty($updates)) {
            $this->bulkUpdateGrowth($updates);
        }
    }

    /**
     * Compute one matchday of growth for a player (pure calculation, no DB).
     *
     * Fractional growth accumulates in `growth_progress`; whole points are
     * applied to `overall_score` once the accumulated progress crosses 1.0.
     * Rounding each matchday's tiny increment (0.07–0.13) to an integer
     * always produced 0, so academy players never developed.
     *
     * @return array{overall_score: int, growth_progress: float}|null Growth to persist, or null if nothing changed
     */
    private function computeGrowth(AcademyPlayer $player, float $seasonRate): ?array
    {
        $gap = $player->potential - $player->overall_score;

        if ($gap <= 0) {
            // Already at (or above) potential: nothing left to grow,
            // drop any stale accumulated progress.
            return (float) ($player->growth_progress ?? 0) > 0
                ? ['overall_score' => $player->overall_score, 'growth_progress' => 0.0]
                : null;
        }

        $progress = (float) ($player->growth_progress ?? 0)
            + $gap * $seasonRate / self::ESTIMATED_MATCHDAYS;

        $whole = (int) floor($progress);
        $applied = min($whole, $gap);

        return [
            'overall_score' => $player->overall_score + $applied,
            // Only consume the progress that was actually applied; any
            // remainder (e.g. capped by potential) stays for next time.
            'growth_progress' => $progress - $applied,
        ];
    }

    /**
     * Bulk update growth (overall_score + growth_progress) using CASE WHEN
     * (1 query instead of N).
     *
     * @param  array<string, array{overall_score: int, growth_progress: float}>  $updates  [id => growth]
     */
    private function bulkUpdateGrowth(array $updates): void
    {
        $ids = array_keys($updates);
        $idList = "'" . implode("','", $ids) . "'";

        $scoreCases = [];
        $progressCases = [];
        foreach ($updates as $id => $growth) {
            $scoreCases[] = "WHEN id = '{$id}' THEN " . (int) $growth['overall_score'];
            // Small positive float: fixed decimals keep the round trip
            // through SQL exact enough to avoid drift.
            $progressCases[] = "WHEN id = '{$id}' THEN " . number_format((float) $growth['growth_progress'], 6, '.', '');
        }

        \Illuminate\Support\Facades\DB::statement("
            UPDATE academy_players
            SET overall_score = CASE " . implode(' ', $scoreCases) . " ELSE overall_score END,
                growth_progress = CASE " . implode(' ', $progressCases) . " ELSE growth_progress END
            WHERE id IN ({$idList})
        ");
    }

    /**
     * Apply a full season of off-screen development to loaned players.
     * Called at season end when loans return.
     */
    public function developLoanedPlayers(Game $game): void
    {
        $loanedPlayers = AcademyPlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->where('is_on_loan', true)
            ->get();

        foreach ($loanedPlayers as $player) {
            // Apply full season growth at loan rate
            $growth = ($player->potential - $player->overall_score) * self::GROWTH_RATE_LOAN;

            $player->update([
                'overall_score' => min($player->potential, (int) round($player->overall_score + $growth)),
            ]);
        }
    }

    /**
     * Return all loaned players to the academy at season end.
     *
     * @return Collection<int, AcademyPlayer> The returned players
     */
    public function returnLoans(Game $game): Collection
    {
        $loanedPlayers = AcademyPlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->where('is_on_loan', true)
            ->get();

        foreach ($loanedPlayers as $player) {
            $player->update(['is_on_loan' => false]);
        }

        return $loanedPlayers;
    }

    /**
     * Mark a player as loaned out.
     */
    public function loanPlayer(AcademyPlayer $player): void
    {
        $player->update(['is_on_loan' => true]);
    }

    /**
     * Dismiss a player from the academy (permanently removed).
     */
    public function dismissPlayer(AcademyPlayer $player): void
    {
        $player->delete();
    }

    /**
     * Promote an academy player to the first team.
     * Creates Player + GamePlayer records and deletes the AcademyPlayer.
     *
     * Runs in a transaction: if the AcademyPlayer delete fails, the player
     * must not exist as both GamePlayer and AcademyPlayer at once.
     */
    public function promoteToFirstTeam(AcademyPlayer $academy, Game $game): GamePlayer
    {
        return DB::transaction(function () use ($academy, $game) {
            $gamePlayer = $this->playerGenerator->create($game, new GeneratedPlayerData(
                teamId: $academy->team_id,
                position: $academy->position,
                overallScore: $academy->overall_score,
                dateOfBirth: $academy->date_of_birth,
                contractYears: 2,
                name: $academy->name,
                nationality: $academy->nationality,
                potential: $academy->potential,
                potentialLow: $academy->potential_low,
                potentialHigh: $academy->potential_high,
                fitnessMin: 85,
                fitnessMax: 100,
                moraleMin: 70,
                moraleMax: 90,
                joinedFrom: \App\Models\UserSquadCareerRecord::ORIGIN_ACADEMY,
            ));

            $gamePlayer->update([
                'number' => $this->squadNumberService->assignNumberForNewPlayer($game, $gamePlayer),
            ]);

            $academy->delete();

            return $gamePlayer;
        });
    }

    /**
     * Auto-promote all academy players who have reached ACADEMY_END age.
     *
     * @return Collection<int, GamePlayer> The promoted players
     */
    public function promoteOveragePlayers(Game $game): Collection
    {
        if (! $game->current_date) {
            return collect();
        }

        $cutoff = PlayerAge::dateOfBirthCutoff(PlayerAge::ACADEMY_END, $game->current_date);

        $overagePlayers = AcademyPlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->where('date_of_birth', '<=', $cutoff)
            ->get();

        return $overagePlayers->map(fn (AcademyPlayer $academy) => $this->promoteToFirstTeam($academy, $game));
    }

    /**
     * Promote the N highest-potential non-loaned academy players to the first team.
     *
     * @return Collection<int, GamePlayer> The promoted players
     */
    public function promoteBestPlayers(Game $game, int $count): Collection
    {
        if ($count <= 0) {
            return collect();
        }

        $candidates = AcademyPlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->where('is_on_loan', false)
            ->orderByDesc('potential')
            ->limit($count)
            ->get();

        return $candidates->map(fn (AcademyPlayer $academy) => $this->promoteToFirstTeam($academy, $game));
    }

    /**
     * Get the expected new arrivals range for a tier.
     *
     * @return array{min: int, max: int}
     */
    public static function getArrivalsRange(int $tier): array
    {
        $config = self::TIER_CONFIG[$tier] ?? self::TIER_CONFIG[0];

        return ['min' => $config[0], 'max' => $config[1]];
    }

    public static function getTierDescription(int $tier): string
    {
        return __('squad.academy_tier_'.(match ($tier) {
            0, 1, 2, 3, 4 => $tier,
            default => 'unknown',
        }));
    }

    public static function getProspectInfo(int $tier): array
    {
        $config = self::TIER_CONFIG[$tier] ?? self::TIER_CONFIG[0];

        return [
            'min_prospects' => $config[0],
            'max_prospects' => $config[1],
        ];
    }

    /**
     * Teams whose academy only produces domestic players (cantera philosophy).
     * Maps team name → exact nationality filter (overrides weighted selection).
     */
    private const CANTERA_TEAMS = [
        'Athletic Club' => 'Spain',
    ];

    /**
     * Roll the shared traits for a youth prospect: position, age, abilities,
     * potential and identity. Quality follows a normal distribution centered
     * on the academy tier's base quality, adjusted by team context — this
     * produces realistic clustering with occasional gems and busts in the tails.
     *
     * The persistence target (AcademyPlayer pool vs reserve-squad GamePlayer)
     * is decided by the caller based on whether the game is filial.
     *
     * @param  array<int, string>  $excludedNames
     * @return array{
     *     position: string,
     *     age: int,
     *     dateOfBirth: \Carbon\Carbon,
     *     technical: int,
     *     physical: int,
     *     potential: int,
     *     potentialLow: int,
     *     potentialHigh: int,
     *     name: string,
     *     nationality: string,
     * }
     */
    private function rollProspectTraits(
        Game $game,
        int $academyTier,
        int $teamMedianTier,
        array $excludedNames,
    ): array {
        $position = $this->selectPosition();

        // Ability mean = academy base quality + team context bonus.
        // Defensive fallbacks: an out-of-range tier degrades to tier 0
        // quality and a neutral (0) team bonus instead of a 500.
        $abilityMean = (self::ACADEMY_BASE_QUALITY[$academyTier] ?? self::ACADEMY_BASE_QUALITY[0])
            + (self::TEAM_CONTEXT_BONUS[$teamMedianTier] ?? 0);

        $age = rand(17, 19);
        $ageCap = match ($age) {
            17 => 72,
            18 => 74,
            19 => 76,
            default => 78,
        };
        $overallScore = $this->sampler->sampleAbility($abilityMean, self::ABILITY_STD_DEV, 50, $ageCap);

        // Single potential pipeline: value the rolled prospect, then hand to
        // PlayerDevelopmentService so academy prospects follow the same logic
        // (incl. reachable cap) as every other player generated mid-game.
        $marketValue = $this->valuationService->overallScoreToMarketValue($overallScore, $age, null, $position);
        $potentialData = $this->developmentService->generatePotential($age, $overallScore, $marketValue);

        $dateOfBirth = $game->current_date->copy()->subYears($age)->subDays(rand(0, 364));

        $teamName = $game->team->name;
        $nationalityFilter = self::CANTERA_TEAMS[$teamName] ?? null;
        $teamCountry = $nationalityFilter ? null : $game->team->country;
        // Basque / Catalan clubs draw on custom Faker providers instead of es_ES
        // so their canteranos get regional names (Etxeberria, Fàbregas, …).
        $region = TeamRegionalOrigins::regionFor($teamName);
        $identity = $this->playerGenerator->pickRandomIdentity(
            $nationalityFilter,
            $teamCountry,
            $excludedNames,
            $region,
        );

        return [
            'position' => $position,
            'age' => $age,
            'dateOfBirth' => $dateOfBirth,
            'overallScore' => $overallScore,
            'potential' => $potentialData['potential'],
            'potentialLow' => $potentialData['low'],
            'potentialHigh' => $potentialData['high'],
            'name' => $identity['name'],
            'nationality' => $identity['nationality'],
        ];
    }

    /**
     * Persist a rolled prospect as an AcademyPlayer pool entry (non-filial games).
     *
     * @param  array<string, mixed>  $traits
     */
    private function persistAsAcademyPlayer(Game $game, array $traits): AcademyPlayer
    {
        return AcademyPlayer::create([
            'id' => Str::uuid()->toString(),
            'game_id' => $game->id,
            'team_id' => $game->team_id,
            'name' => $traits['name'],
            'nationality' => $traits['nationality'],
            'date_of_birth' => $traits['dateOfBirth'],
            'position' => $traits['position'],
            'overall_score' => $traits['overallScore'],
            'potential' => $traits['potential'],
            'potential_low' => $traits['potentialLow'],
            'potential_high' => $traits['potentialHigh'],
            'appeared_at' => $game->current_date,
            'is_on_loan' => false,
            'joined_season' => (int) $game->season,
            'initial_overall' => $traits['overallScore'],
        ]);
    }

    /**
     * Persist a rolled prospect as a full GamePlayer on the reserve squad
     * (filial games). The reserve squad is the source of truth for filial
     * players, so prospects skip the AcademyPlayer pool entirely.
     *
     * @param  array<string, mixed>  $traits
     */
    private function persistAsReservePlayer(Game $game, array $traits): GamePlayer
    {
        return $this->playerGenerator->create($game, new GeneratedPlayerData(
            teamId: $game->reserve_team_id,
            position: $traits['position'],
            overallScore: $traits['overallScore'],
            dateOfBirth: $traits['dateOfBirth'],
            contractYears: 2,
            name: $traits['name'],
            nationality: $traits['nationality'],
            potential: $traits['potential'],
            potentialLow: $traits['potentialLow'],
            potentialHigh: $traits['potentialHigh'],
            fitnessMin: 85,
            fitnessMax: 100,
            moraleMin: 70,
            moraleMax: 90,
            joinedFrom: \App\Models\UserSquadCareerRecord::ORIGIN_ACADEMY,
        ));
    }

    /**
     * Get the median PlayerTier of the first team's squad.
     */
    private function getTeamMedianTier(Game $game): int
    {
        $tiers = GamePlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->pluck('tier')
            ->sort()
            ->values();

        if ($tiers->isEmpty()) {
            return 2; // fallback for empty squads
        }

        $midIndex = intdiv($tiers->count(), 2);

        return $tiers[$midIndex];
    }

    /**
     * Get names of every existing player in the game — all first-team squads
     * (any team, plus free agents) and all academy rosters. Game-wide scope is
     * required so that a new canterano's name doesn't collide with a player on
     * another team (issue #819).
     *
     * @return string[]
     */
    private function getExistingPlayerNames(Game $game): array
    {
        $playerNames = GamePlayer::where('game_id', $game->id)
            ->pluck('name')
            ->toArray();

        $academyNames = AcademyPlayer::where('game_id', $game->id)
            ->pluck('name')
            ->toArray();

        return array_merge($playerNames, $academyNames);
    }

    private function selectPosition(): string
    {
        $random = rand(1, 100);

        foreach (self::POSITION_GROUPS as $group) {
            $random -= $group['weight'];
            if ($random <= 0) {
                return $group['positions'][array_rand($group['positions'])];
            }
        }

        return 'Central Midfield';
    }
}
