<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Club social media ("Redes del club"):
     * - games.social_hype: 0-100 hype generated by exciting official
     *   announcements (signings...). Boosts home attendance while it lasts.
     * - social_posts.parent_post_id: threads official club announcements
     *   with their fan replies.
     */
    public function up(): void
    {
        Schema::table('games', function (Blueprint $table) {
            $table->integer('social_hype')->default(0);
        });

        Schema::table('social_posts', function (Blueprint $table) {
            $table->uuid('parent_post_id')->nullable()->after('id');
            $table->foreign('parent_post_id')
                ->references('id')->on('social_posts')
                ->nullOnDelete();
        });
    }

    public function down(): void
    {
        Schema::table('social_posts', function (Blueprint $table) {
            $table->dropForeign(['parent_post_id']);
            $table->dropColumn('parent_post_id');
        });

        Schema::table('games', function (Blueprint $table) {
            $table->dropColumn('social_hype');
        });
    }
};
