<?php

// Mapa equipo -> región (comunidad autónoma) para patrocinios locales.
// Un patrocinador con 'region' solo puede patrocinar a equipos de su región.
// Equipos sin región mapeada conservan el comportamiento anterior (todo el país).

return [
    'ES' => [
        "AD Villaviciosa de Odón" => "madrid",
        "Alhama CF" => "murcia",
        "As Celtas" => "galicia",
        "Athletic Club" => "pais-vasco",
        "Athletic Club B" => "pais-vasco",
        "Atlético de Madrid" => "madrid",
        "Atlético de Madrid B" => "madrid",
        "Balears FC" => "baleares",
        "Bizkerre FT" => "pais-vasco",
        "Burgos CF" => "castilla-leon",
        "CA Osasuna" => "navarra",
        "CA Osasuna B" => "navarra",
        "CD Argual" => "canarias",
        "CD Arratia" => "pais-vasco",
        "CD Femarguín" => "canarias",
        "CD Getafe Femenino" => "madrid",
        "CD Guiniguada Apolinario" => "canarias",
        "CD Samper" => "aragon",
        "CD Tenerife Femenino B" => "canarias",
        "CE Europa" => "catalunya",
        "CF Pozuelo de Alarcón" => "madrid",
        "CFF Olympia Las Rozas" => "madrid",
        "CP Cacereño" => "extremadura",
        "Cacereño Femenino Atlético" => "extremadura",
        "Club de Fútbol Oviedo Moderno Universida" => "asturias",
        "Costa Adeje Tenerife Egatesa" => "canarias",
        "Córdoba CF" => "andalucia",
        "Deportivo Alavés" => "pais-vasco",
        "Dépor ABANCA B" => "galicia",
        "Dépor Abanca" => "galicia",
        "EMF Fuensalida" => "madrid",
        "Elche CF" => "valencia",
        "FC Badalona Women" => "catalunya",
        "FC Barcelona" => "catalunya",
        "FC Barcelona B" => "catalunya",
        "FC Barcelona C" => "catalunya",
        "FC Ona Sant Adrià" => "catalunya",
        "Fundación Albacete" => "castilla-la-mancha",
        "Granada CF" => "andalucia",
        "Granada CF B" => "andalucia",
        "Levante UD" => "valencia",
        "Levante UD B" => "valencia",
        "Logroño United" => "la-rioja",
        "Madrid CFF" => "madrid",
        "Madrid CFF B" => "madrid",
        "Málaga CF" => "andalucia",
        "RCD Espanyol" => "catalunya",
        "RCD Espanyol B" => "catalunya",
        "Rayo Vallecano" => "madrid",
        "Real Avilés CF" => "asturias",
        "Real Betis Balompié" => "andalucia",
        "Real Madrid B" => "madrid",
        "Real Madrid CF" => "madrid",
        "Real Murcia" => "murcia",
        "Real Racing Club de Santander" => "cantabria",
        "Real Sociedad" => "pais-vasco",
        "Real Sociedad B" => "pais-vasco",
        "Real Unión de Tenerife Santa Cruz" => "canarias",
        "SD Eibar" => "pais-vasco",
        "SD Eibar B" => "pais-vasco",
        "SD Huesca" => "aragon",
        "SE AEM" => "catalunya",
        "Sevilla FC" => "andalucia",
        "Sportextremadura CD" => "extremadura",
        "Sporting de Gijón" => "asturias",
        "Sporting de Huelva" => "andalucia",
        "UD Almería" => "andalucia",
        "Valencia CF B" => "valencia",
        "Valencia CF Femenino" => "valencia",
        "Victoria CF" => "galicia",
        "Villarreal CF" => "valencia",
        "Zaragoza CFF" => "aragon",
    ],
];
